### ISSUE TITLE
get_watermark.py array out of bounds

### ISSUE THREAD

**Issue by ryanhex53** [m3at/video-watermark-removal#2]
ryan@LAPTOP-HLNGJ2BD:~$ ./remove_watermark.sh /mnt/c/Users/Ryan/Desktop/video.mp4
Getting key frames...
Extracting frames (up to: 50)...
Extracting watermark...
Traceback (most recent call last):
  File "./get_watermark.py", line 26, in <module>
    dx = np.gradient(images, axis=1).mean(axis=3)
  File "<__array_function__ internals>", line 180, in gradient
  File "/home/ryan/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 1150, in gradient
    axes = _nx.normalize_axis_tuple(axis, N)
  File "/home/ryan/.local/lib/python3.8/site-packages/numpy/core/numeric.py", line 1397, in normalize_axis_tuple
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
  File "/home/ryan/.local/lib/python3.8/site-packages/numpy/core/numeric.py", line 1397, in <listcomp>
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
numpy.AxisError: axis 1 is out of bounds for array of dimension 1

**Comment by m3at** [comment]
That's odd, is this specific to this particular video? If so can you share some infos about it (example using ffprobe)?

**Comment by ryanhex53** [comment]
`ffprobe video.mp4`
<pre>
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'video.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.76.100
  Duration: 00:00:24.44, start: 0.000000, bitrate: 4723 kb/s
  Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1080x1920 [SAR 1:1 DAR 9:16], 4587 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 129 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
</pre>

**Comment by m3at** [comment]
Sorry look like I missed a small issue in your #1 PR, the escaping around the regex was wrong and resulted in no frame being extracted (fixed).
So it look like the error is something else, can you pull and re-try?

**Comment by ryanhex53** [comment]
It works but not perfect, this issues can be closed.

Original             |  Output
:-------------------------:|:-------------------------:
![20220824105457](https://user-images.githubusercontent.com/360426/186310494-135b4ebb-51a1-49e3-b1c0-555e849fe933.png)  |  ![20220824105551](https://user-images.githubusercontent.com/360426/186311511-7d89d7ef-83c0-47ed-b135-3e0955fbdfea.png)
