### ISSUE TITLE
Pink frame in output video

### ISSUE THREAD

**Issue by edo0** [m3at/video-watermark-removal#3]
First of all, thank you very much for this nifty tool!

There is only one issue, and that is that every output will present the pink frame you can see in the picture.
Is there any way to get rid of it? Thank you in advance!!

![image](https://user-images.githubusercontent.com/16632292/191990802-2b78d615-b35d-405e-9381-7b8c6fb2697f.png)

I am using it on Arch Linux

**Comment by m3at** [comment]
That's odd, I don't see this issue on my side sorry 🤔 (just tried with: python 3..10.6, numpy 1.23.2, scipy 1.9.1, imageio 2.22.0)

I'm not sure what's happening, maybe there was some small padding in the source video? The pink filling is strange though.
As a stop-gap you might want to just crop it out? Something like:
```sh
# Removing 4 pixels on each sides
ffmpeg -i in.mp4 -filter:v "crop=in_w-8:in_h-8:4:4" -c:a copy out.mp4
```

**Comment by m3at** [comment]
I'm going to close this, but feel free to re-open if it's still relevant
