### ISSUE TITLE
Watermark is not removed instead is smudged

### ISSUE THREAD

**Issue by tfrazao-tech** [m3at/video-watermark-removal#5]
The result of the output video leaves a smudged image of the watermark it does not remove it all and in my case, it was just a word in the upper right corner of the video.

**Comment by m3at** [comment]
That's too bad. Do you have a screenshot, ideally of the source video then the results?
The parameters can probably be tweaked to make it work, but still that script is very basic so it's bound to have limitations…

**Comment by m3at** [comment]
I'll close for now but feel free to reopen with an example if it's still relevant 🙂
