### ISSUE TITLE
Unknown cover type: 0x1

### ISSUE THREAD

**Issue by 2shou** [m3at/video-watermark-removal#6]
(base) ➜  video-watermark-removal git:(main) ./remove_watermark.sh ~/Downloads/20231011/20231011.mp4
Getting key frames...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x144e05bf0] Unknown cover type: 0x1.
xargs: shuf: No such file or directory

**Comment by m3at** [comment]
> `xargs: shuf: No such file or directory`

You seem to be missing the [shuf](https://man7.org/linux/man-pages/man1/shuf.1.html) program. If you're on MacOS, you could install it with ex. `brew install coreutils` (it will be then linked as `gshuf` instead of `shuf`)
