### ISSUE TITLE
Watermark removal not working

### ISSUE THREAD

**Issue by Silver-will** [m3at/video-watermark-removal#8]
Running the script and it gives me the following error messages and aborts:
```
$ bash remove_watermark.sh mt.mp4 /c/Katsura 50
Getting key frames...
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001d03187e3c0] st: 1 edit list: 1 Missing key frame while searching for timestamp: 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001d03187e3c0] st: 1 edit list 1 Cannot find an index entry before timestamp: 0.
Extracting frames (up to: 50)... Skipping unrecognize timing: N/A
0 Skipping unrecognize timing: N/A

1 frames extracted, need at least 2, aborting.
```

**Comment by NigelHiggs30** [comment]
Same

**Comment by m3at** [comment]
Still works for me, using the ffmpeg 6.1.1_6 (latest on MacOS 14.4). Try updating your ffmpeg version?

If it still fails, try to run the command directly and share the error:
```bash
ffprobe -select_streams v -skip_frame nokey -show_frames -show_entries frame=pkt_dts_time <YOUR_FILE>
```
If it fails only on this video, please share details about the file

**Comment by chungimungi** [comment]
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/chedi/aiisc/VideoFusion/mets.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:04.00, start: 0.000000, bitrate: 582 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 256x256, 580 kb/s, 8 fps, 8 tbr, 16384 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
[FRAME]
pkt_dts_time=N/A
[SIDE_DATA]
side_data_type=H.26[45] User Data Unregistered SEI message
[/SIDE_DATA]
[/FRAME]
[FRAME]
pkt_dts_time=N/A
[/FRAME]



https://github.com/m3at/video-watermark-removal/assets/90822297/1c4b67da-ae3f-42ad-aeda-382545922d3b

i have added the  video as well
